services:
  db:
    container_name: tys-db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - project.env
  web:
    container_name: tys-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media
    ports:
      - "8000"
    expose:
      - 8000
    env_file:
      - project.env
    depends_on:
      - db

  nginx:
    container_name: tys-nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "1520:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media

volumes:
  postgres-data:
  staticfiles:
  mediafiles: